### ISSUE TITLE
upgrading from Linux Mint 20.1 to 20.2 blanket no longer works 

### ISSUE THREAD

**Issue by arax-1238** [rafaelmardojai/blanket#146]
With Mint 20.1 (installated using stable PPA stable releases) worked greatly!

Now with **Mint 20.2  does not work.  Here the errors**:

io@glutin:~$ blanket
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] File o directory non esistente: '/var/crash/_usr_bin_blanket.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 140, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/share/blanket/blanket/window.py", line 254, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] File o directory non esistente: '/var/crash/_usr_bin_blanket.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 140, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/share/blanket/blanket/window.py", line 254, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by rafaelmardojai** [comment]
I can't figure out what is causing the error from what you have pasted. Also you're running the development version, because the errors reference to "presets" code which hasn't been released. From what source have you installed Blanket?

**Comment by arax-1238** [comment]
I was using daily buids ppa. Now I removed it and **using stable releases** ppa:apandada1/blanket **it works perfectly**.

Thank you very much for your help and for your great work !
