### ISSUE TITLE
Blanket installed from Arch repository does not display any sounds.

### ISSUE THREAD

**Issue by salperinlea** [rafaelmardojai/blanket#233]
OS: Arch Linux 250-3-4, running kernel 5.16.8 with KDE Plasma 5.24.0 as DE.
Blanket 0.5.0-1
*** **** *** *** ***
Running from command line, the following errors are thrown:

```
/usr/share/blanket/blanket/sound.py:86: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_volume(0)
/usr/share/blanket/blanket/sound.py:89: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_uri(self.sound.uri)
/usr/share/blanket/blanket/sound.py:94: Warning: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed
  self.pipeline = self.get_pipeline()
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'
/usr/share/blanket/blanket/widgets.py:206: Warning: g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)

(com.rafaelmardojai.Blanket:29522): Gtk-CRITICAL **: 15:18:47.302: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:29522): Gtk-CRITICAL **: 15:18:47.302: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
/usr/share/blanket/blanket/widgets.py:206: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__


    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'
 
```
Resultingly, the interface looks like this:
![Blanket_bug](https://user-images.githubusercontent.com/40773827/153773627-71b7dddb-46a6-49d8-824c-0161bdad23ca.png)

**Comment by ksdrummer** [comment]
I confirm I have the same problem on arch up to date, since few days.
(Blanket 0.5.0)

**Comment by Chipsterjulien** [comment]
Same here with ArchLinux

**Comment by kpiche** [comment]
It's the gstreamer 1.20 upgrade.  It works again if you downgrade packages to 1.18.5.

**Comment by tio-trom** [comment]
Same here even the flatpak doesn't work...

**Comment by TomasKukumberg** [comment]
@tio-trom Strange, flatpak works for me, but arch repository one does not

**Comment by tio-trom** [comment]
Very weird because flatpaks should, in theory, contain all packages for an "app". I am on arch and for me it does not work.

**Comment by rafaelmardojai** [comment]
> Very weird because flatpaks should, in theory, contain all packages for an "app". I am on arch and for me it does not work.

It's showing the same error than the OP? 

Flatpak is working fine for me.

**Comment by tio-trom** [comment]
Yes, same:

![2022-02-28_14-27](https://user-images.githubusercontent.com/38043315/155991141-fce65415-03ce-437b-9549-a85d693affba.png)

**Comment by rafaelmardojai** [comment]
Doesn't seems to be printing the same error...

**Comment by tio-trom** [comment]
Ah I apologize I thought about the way Blanket looks, it seems broken in the same way visually and functionally.

**Comment by rafaelmardojai** [comment]
> Ah I apologize I thought about the way Blanket looks, it seems broken in the same way visually and functionally.

No problem. Blanket will look like that if something failed but still allowed it to show the window.

**Comment by dxdns** [comment]
i have the same problem here

**Comment by amithiel** [comment]
same here on arch. man i love this app! really hope you can fix it!
downgrading gstreamer is not really wise
cheers

**Comment by jubalh** [comment]
Arch people are the new Ubuntu people. Everybody feels like commenting "for me too!!! on arch btw!!". Instead of just pushing that thumbs up on the first entry.

**Comment by rafaelmardojai** [comment]
Hopefully next version will be ported to use `Gst.Play` from `gstreamer 1.20` (I'm wanting for it to be in the master runtime) and maybe will fix the problem.

I will ask here for testers when working on this.

**Comment by tio-trom** [comment]
I just wanted to let you know that flatpak works for me. Was a matter of the old package running in the background.

**Comment by wangxa** [comment]
This is the same error as mentioned in Problem #199.

**Comment by jjgalvez** [comment]
same here, getting the same error on Arch, flatpak works as expected.

**Comment by wangwang1983** [comment]
So when will the problem be solved?

**Comment by rafaelmardojai** [comment]
[4cc08174b486f7b78c57633877c79f6a910f28ff] should fix the issue, please test.

**Comment by jubalh** [comment]
Using blanket 0.5.0 patched with https://github.com/rafaelmardojai/blanket/commit/4cc08174b486f7b78c57633877c79f6a910f28ff] I get:

```
blanket
/usr/share/blanket/blanket/sound.py:90: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_volume(0)
/usr/share/blanket/blanket/sound.py:93: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_uri(self.sound.uri)
/usr/share/blanket/blanket/sound.py:98: Warning: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed
  self.pipeline = self.get_pipeline()
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'
/usr/share/blanket/blanket/widgets.py:206: Warning: g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.502: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.502: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
/usr/share/blanket/blanket/widgets.py:206: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.503: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.503: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.504: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.504: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.505: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.505: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.505: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.505: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.506: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.506: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.507: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.507: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.508: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.508: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.509: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.509: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.510: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.510: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.511: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.511: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.511: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.511: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.512: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.512: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 99, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.513: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:63741): Gtk-CRITICAL **: 22:30:34.513: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
```

**Comment by yochananmarqos** [comment]
@rafaelmardojai Yes, that works.

@jubalh No idea how you're "patching" the stable version with one commit, but it won't work by itself. You'll need to install directly from the master branch or install the `blanket-git` AUR package if you're using Arch.

**Comment by rafaelmardojai** [comment]
> Using blanket 0.5.0 patched with https://github.com/rafaelmardojai/blanket/commit/4cc08174b486f7b78c57633877c79f6a910f28ff] I get:

Please build from master. 0.5.0 is 43 commits behind master and those changes may influence.

**Comment by rafaelmardojai** [comment]
> Yes, that works.

@yochananmarqos Nice, will prepare to release this week then.

**Comment by yochananmarqos** [comment]
@rafaelmardojai Well, there is a separate issue that should be addressed:

```
/usr/share/blanket/blanket/sound.py:6: PyGIWarning: GstPlay was imported without specifying a version first. Use gi.require_version('GstPlay', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository.GstPlay import Play as GStreamerPlay
```

**Comment by rafaelmardojai** [comment]
@yochananmarqos see: https://github.com/rafaelmardojai/blanket/issues/199#issuecomment-1082316547

**Comment by jubalh** [comment]
> Please build from master. 0.5.0 is 43 commits behind master and those changes may influence.

In your [message](https://github.com/rafaelmardojai/blanket/issues/233#issuecomment-1082016094) you mentioned that this commit should fix it. So obvisously I took this commit only.

**Comment by rafaelmardojai** [comment]
@jubalh Yeah sorry, probably my comment was misleading.

**Comment by graves501** [comment]
Thanks for creating this application, really cool idea! It was mentioned in [The Linux Experiment's video](https://www.youtube.com/watch?v=O5As4HocCrw), so I wanted to try it out. Sadly on `Manjaro` it's the same issue like mentioned above, but the `flatpak` worked perfectly fine!

**Comment by Phundrak** [comment]
I installed blanket from both the community repo and from the AUR (with `blanket-git`). While the former do not show any sound, as others have shown above, `blanket-git` seems to work. [Here](https://0x0.st/obZS.txt) is the terminal output of blanket 0.5.0-1. The output of `blanket-git` as of commit de9e190 simply outputs this:
```
/usr/share/blanket/blanket/sound.py:6: PyGIWarning: GstPlay was imported without specifying a version first. Use gi.require_version('GstPlay', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository.GstPlay import Play as GStreamerPlay
```

**Comment by amatosg** [comment]
In my case neither seem to work. Both versions show an empty list. The official Arch package show no error, while the AUR package shows only the warning.

**Comment by shmu26** [comment]
I see this same issue on Kubuntu 22.04, when installed from PPA. The Flatpak version works as expected.

**Comment by rafaelmardojai** [comment]
> I see this same issue on Kubuntu 22.04, when installed from PPA. The Flatpak version works as expected.

Looks like the PPA hasn't be updated to `0.6.0`.

**Comment by rafaelmardojai** [comment]
Closing this since `0.6.0` is in the arch repos.
