### ISSUE TITLE
Issues while running

### ISSUE THREAD

**Issue by pjalsGit** [rafaelmardojai/blanket#240]
When running from GNOME Builder, it looks like its ran from root, and some transparency effects don't work:
![image](https://user-images.githubusercontent.com/25231103/158347325-0b7eb066-afb3-4fc6-8966-a8ca8e5fcbed.png)

also, when trying to add a custom sound it doesn't open the file chooser and errors in the terminal with:
```
Traceback (most recent call last):
  File "/app/share/blanket/blanket/window.py", line 251, in _on_add_sound_clicked
    self.open_audio()
  File "/app/share/blanket/blanket/window.py", line 212, in open_audio
    response = self.filechooser.run()
AttributeError: 'FileChooserNative' object has no attribute 'run'
```

When running from a meson build, it errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/blanket", line 39, in <module>
    from blanket import main
  File "/usr/local/share/blanket/blanket/main.py", line 11, in <module>
    gi.require_version('Adw', '1')
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available
```

**Comment by pjalsGit** [comment]
> Maybe you're missing GPU drivers in your Flatpak installation?

Yeah, probably, my AMDGPU setup is pretty broken.

> You need `libadwaita` installed if you're comping by yourself in the host.

Thanks!
