### ISSUE TITLE
No Sounds Listed

### ISSUE THREAD

**Issue by ThePademelon** [rafaelmardojai/blanket#253]
When I start the application I get a GUI with no sounds in it. I think there was an update recently and it was definitely working before that.
![image](https://user-images.githubusercontent.com/17604430/164873128-627cee36-a1fb-436e-95c1-81ff87744525.png)

Here's the output from the terminal.
```
[nim@pc-gamma ~]$ blanket

(blanket:3657): dbind-WARNING **: 12:52:43.942: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
/usr/share/blanket/blanket/sound.py:86: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_volume(0)
/usr/share/blanket/blanket/sound.py:89: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_uri(self.sound.uri)
/usr/share/blanket/blanket/sound.py:94: Warning: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed
  self.pipeline = self.get_pipeline()
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'
/usr/share/blanket/blanket/widgets.py:206: Warning: g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.084: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.084: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
/usr/share/blanket/blanket/widgets.py:206: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.085: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.085: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.085: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.085: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.086: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.086: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.087: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.087: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.087: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.087: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.088: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.088: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.088: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.088: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.089: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.089: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.090: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.090: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.090: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.090: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.091: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.091: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.091: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.091: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 209, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 70, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.092: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(com.rafaelmardojai.Blanket:3657): Gtk-CRITICAL **: 12:52:44.092: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
```

Thanks!

**Comment by ThePademelon** [comment]
I updated to v0.6.0 from v0.5.0 and that seems to have fixed it.

**Comment by rafaelmardojai** [comment]
> I updated to v0.6.0 from v0.5.0 and that seems to have fixed it.

Yup this is an issue with GStreamer 1.20 (see #199), `0.6.0` has been released with a fix for that.
