### ISSUE TITLE
Blanket is not working on Fedora 35 with Waylent

### ISSUE THREAD

**Issue by isurunix** [rafaelmardojai/blanket#257]
It seems Blanket from Copr repo does not work in Fedora with Wayland.
This is probably because missing libadawita according to the error shown

```
Traceback (most recent call last):
  File "/usr/bin/blanket", line 39, in <module>
    from blanket import main
  File "/usr/share/blanket/blanket/main.py", line 11, in <module>
    gi.require_version('Adw', '1')
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available
```

## Steps to reproduce

1. Enable Copr repo
2. Install Blanket
3. Run Blanket

## Environment

- OS: Fedora 35
- Desktop Environment: Gnome with Wayland

**Comment by feltcat** [comment]
I just got the same issue with X11, and installing the libadwaita package did indeed fix it.

(As an aside: it would probably be a good idea to add a --version command line option to Blanket)

**Comment by werdahias** [comment]
you might need to install the fedora equivalent of gir1.2-adw-1 (debian package) which contains the gir file for libadwaita that blanket needs
