### ISSUE TITLE
[ArchLinux] Blanket not launching anymore - Segment violation ('core' generated)

### ISSUE THREAD

**Issue by KibaGasteiz** [rafaelmardojai/blanket#369]
The program runs when using 'sudo' but not as a normal user anymore.

`blanket

Violación de segmento ('core' generado)
`

`sudo blanket

sys:1: Warning: cannot register existing type 'GtkWidget'
sys:1: Warning: cannot add class private field to invalid type '<invalid>'
sys:1: Warning: cannot add private field to invalid (non-instantiatable) type '<invalid>'
sys:1: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
sys:1: Warning: cannot register existing type 'GtkBuildable'
sys:1: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
sys:1: Warning: g_once_init_leave_pointer: assertion 'result != 0' failed
sys:1: Warning: g_param_spec_object: assertion 'g_type_is_a (object_type, G_TYPE_OBJECT)' failed
sys:1: Warning: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed
sys:1: Warning: g_param_spec_ref_sink: assertion 'G_IS_PARAM_SPEC (pspec)' failed
sys:1: Warning: g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 82, in do_startup
    self.mpris = MPRIS(self)
                 ^^^^^^^^^^^
  File "/usr/share/blanket/blanket/mpris.py", line 158, in __init__
    self.__bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-spawn-exit-error-quark: Error al lanzar («spawn») el comando «dbus-launch --autolaunch=0d22969cbc5b48d8850390e7269e6695 --binary-syntax --close-stderr»: El proceso hijo terminó con el código 1 (1)

(python3:10406): Gtk-WARNING **: 17:42:27.019: Unable to acquire session bus: Error al lanzar («spawn») el comando «dbus-launch --autolaunch=0d22969cbc5b48d8850390e7269e6695 --binary-syntax --close-stderr»: El proceso hijo terminó con el código 1

(python3:10406): dconf-WARNING **: 17:42:35.484: failed to commit changes to dconf: Error al lanzar («spawn») el comando «dbus-launch --autolaunch=0d22969cbc5b48d8850390e7269e6695 --binary-syntax --close-stderr»: El proceso hijo terminó con el código 1

(python3:10406): dconf-WARNING **: 17:42:35.484: failed to commit changes to dconf: Error al lanzar («spawn») el comando «dbus-launch --autolaunch=0d22969cbc5b48d8850390e7269e6695 --binary-syntax --close-stderr»: El proceso hijo terminó con el código 1
`

**Comment by KibaGasteiz** [comment]
Hi, sorry about this, the program worked fine for months now, i assume it was some package not compatible with this one for a moment.
Closing this issue now. Thank you for reminding me ;)
