### ISSUE TITLE
"Please call Gst.init(argv) before using GStreamer"

### ISSUE THREAD

**Issue by yochananmarqos** [rafaelmardojai/blanket#6]
I built 0.1.0 from source on Manjaro Linux. `gst-python` doesn't seem to be very happy running it:

```
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 49, in do_startup
    Gst.init()
TypeError: init() missing 1 required positional argument: 'argv'
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 127, in _create_sound_widget
    widget = SoundRow(sound, self.model, self.settings)
  File "/usr/share/blanket/blanket/widgets.py", line 48, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 54, in __init__
    self.playbin = Gst.ElementFactory.make('playbin', self.sound.name)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gst.py", line 246, in make
    return Gst.ElementFactory.make(factory_name, instance_name)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gst.py", line 605, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer
/usr/share/blanket/blanket/widgets.py:124: Warning: g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)

(blanket:1504180): Gtk-CRITICAL **: 13:55:09.203: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(blanket:1504180): Gtk-CRITICAL **: 13:55:09.203: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
/usr/share/blanket/blanket/widgets.py:124: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 127, in _create_sound_widget
    widget = SoundRow(sound, self.model, self.settings)
  File "/usr/share/blanket/blanket/widgets.py", line 48, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 54, in __init__
    self.playbin = Gst.ElementFactory.make('playbin', self.sound.name)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gst.py", line 246, in make
    return Gst.ElementFactory.make(factory_name, instance_name)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gst.py", line 605, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer

(blanket:1504180): Gtk-CRITICAL **: 13:55:09.204: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by yochananmarqos** [comment]
That commit made no difference, unfortunately.

**Comment by rafaelmardojai** [comment]
[208c67a5687a471b74978f63943f83ffb61600b0] Does something? 

If not, latter i will build dependencies from source to reproduce. With Flatpak everything works well.

**Comment by yochananmarqos** [comment]
Yes, that solved the issue. Thanks!
